name: sfedu_project
description: Приложение для организации рабочего дня с уведомлениями
publish_to: "none" # Это частный проект, не публикуем в pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Управление состоянием (BLoC)
  flutter_bloc: ^9.0.0

  # Локальное хранилище (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Уведомления (Local Notifications)
  flutter_local_notifications: ^18.0.1 # Используем стабильную версию

  # Инструменты для работы с датами и временем
  intl: ^0.20.2
  timezone: ^0.10.0

  # Поддержка путей к файлам (для Hive)
  path_provider: ^2.1.1

  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Генерация адаптеров для Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff" # (для Android 8+)
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
