// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkA2W-ebJjYQZmecSW_nSxoSIq3FXy0zs',
    appId: '1:299762152510:web:11a534f7c52a81a2990d6f',
    messagingSenderId: '299762152510',
    projectId: 'sfedu-project-cbe0b',
    authDomain: 'sfedu-project-cbe0b.firebaseapp.com',
    storageBucket: 'sfedu-project-cbe0b.firebasestorage.app',
    measurementId: 'G-4KWM22DL4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOU3EmkmfDoEwfVJNIpMofXxyeWzHE7sM',
    appId: '1:299762152510:android:449e656175f60946990d6f',
    messagingSenderId: '299762152510',
    projectId: 'sfedu-project-cbe0b',
    storageBucket: 'sfedu-project-cbe0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbVvHD4BguNGV5K_rB2wEUPZNb_FrY4k',
    appId: '1:299762152510:ios:0e83856b8a15f229990d6f',
    messagingSenderId: '299762152510',
    projectId: 'sfedu-project-cbe0b',
    storageBucket: 'sfedu-project-cbe0b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbVvHD4BguNGV5K_rB2wEUPZNb_FrY4k',
    appId: '1:299762152510:ios:0e83856b8a15f229990d6f',
    messagingSenderId: '299762152510',
    projectId: 'sfedu-project-cbe0b',
    storageBucket: 'sfedu-project-cbe0b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkA2W-ebJjYQZmecSW_nSxoSIq3FXy0zs',
    appId: '1:299762152510:web:2a8eb6b6497e3417990d6f',
    messagingSenderId: '299762152510',
    projectId: 'sfedu-project-cbe0b',
    authDomain: 'sfedu-project-cbe0b.firebaseapp.com',
    storageBucket: 'sfedu-project-cbe0b.firebasestorage.app',
    measurementId: 'G-6DXD49HZ1S',
  );
}
